defaults:
  - _self_
  - model: unet_3d
  - scheduler: continuousddpm
  - paths: default

# Seed for random number generators
seed: 0
samples_per: 1
load_path: ipsl_tas_dcpp_4.pt
esm: IPSL
scenario: dcpp
gen_mode: val  # Either gen/val/test
batch_size: 1
sample_steps: 250
start_year: 1961
end_year: 1971
variables: [tas,pr]   
save_name: null  # Only set a save name if you want something special added to your save path
# spatial_resolution: null

dataset:
  _target_: data.climate_dataset.ClimateDataset
  seq_len: 120

accelerator:
  mixed_precision: fp16
